# Generated by Django 4.2.5 on 2023-09-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='estado',
            field=models.CharField(choices=[('Activado', 'Activado'), ('Desactivado', 'Desactivado'), ('Eliminado', 'Eliminado')], default='Activado', max_length=20),
        ),
    ]
